---
- name: Set ipv6 on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Check if service exists
  stat:
    path: /usr/lib/systemd/system/firewalld.service
  ignore_errors: yes
  register: service_status

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: service_status.stat.exists

- name: Ensure temp download directory exist
  file:
    state: directory
    path: "{{ vagrant_tmp_dir }}"

- name: Download vagrant
  get_url:
    url: "{{ vagrant_url_rpm }}"
    dest: "{{ vagrant_tmp_rpm }}"
    checksum: "sha256:{{ vagrant_checksum_sha256 }}"

- name: Install list of packages (RHEL/CentOS)
  yum:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ vagrant_tmp_rpm }}"
