---
- name: Checking VirtualBox is installed or not
  shell: which virtualbox
  register: result
  changed_when: False
  ignore_errors: True

- block:

  - name: Add VirtualBox repo file
    get_url:
      url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo

  - name: Cleanup repo caches
    shell: |
      yum clean all
      yum repolist

  - name: Install dependency packages
    yum:
      name: "{{ items }}"
      state: latest
    register: install_packages
    until: install_packages is success
    retries: 5
    delay: 2
    vars:
      items:
      - gcc
      - make
      - kernel-headers

  - name: Install additional packages
    shell: >
      warn=no
      yum install -y kernel-devel-`uname -r`
    when:
      - run_install_kernel_devel

  - name: Install VirtualBox
    yum:
      name: "{{ virtualbox_pkgname }}"
      enablerepo: virtualbox
      state: "{{ virtualbox_version }}"

  - name: Initialize VirtualBox
    command: /sbin/vboxconfig

  when: result is failed
