---
- name: Checking VirtualBox is installed or not
  command: which virtualbox
  register: result
  changed_when: False
  ignore_errors: True

- block:

  - name: Add VirtualBox repo file
    get_url:
      url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo

  - name: Cleanup repo caches
    command: |
      yum clean all
      yum repolist

  - name: Install dependency packages
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - name: gcc
        state: latest
      - name: make
        state: latest
      - name: kernel-headers
        state: latest

  - name: Install additional packages
    command: yum install -y kernel-devel-`uname -r`
    when:
    - run_install_kernel_devel

  - name: Install VirtualBox
    yum:
      name: "{{ virtualbox_pkgname }}"
      state: "{{ virtualbox_version }}"

  - name: Initialize VirtualBox
    command: /sbin/vboxconfig

  when: result | failed
