---
- name: Set ipv6 on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Check if service exists
  stat:
    path: /usr/lib/systemd/system/firewalld.service
  ignore_errors: yes
  register: service_status

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: service_status.stat.exists

- name: Install openssh package
  yum:
    name: openssh
    state: present

- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f {{ ssh_keypair_dir }}/{{ ssh_key }} -q -N ""
  args:
    creates: "{{ ssh_keypair_dir }}/{{ ssh_key }}"

